---
title: "EDS-212_day2_part2"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Plotting functions in ggplot2

```{r}
fx = function(x){3 * x^2 + 4}
# --- c(1, 100) creates a vector of two values 1 and 100; c = concatenate function
# --- data.frame - is required to create a table with variables & values
ggplot(data.frame(x1 = c(1, 100)), aes(x = x1)) + 
  geom_function(fun = fx)
```

## Partial derivatives

```{r}
#--- use expression for derivatives
fxyz = expression(2 * x * y + 3 * (x^2) * (z^3))

#--- partial derivative function with respect to y
dfdy = D(fxyz, 'y')

dfdy
```

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Penguins plot

1.  Define that you are plotting ggplot
2.  Define the data used for a chart (data.frame)
3.  Define the parameters

```{r}
# --- aes is reserved to mapping variable to chart estetics, based on the chart variable.
# --- if the changes are not based on a variable it should be outside the aes

ggplot(data.frame(penguins), aes(x = body_mass_g, 
                                 y = flipper_length_mm, 
                                 color = species)) +
  geom_point() +
  labs(x = "Flipper length, mm", 
       y = "Body mass, g", 
       title = "Palmer penguins body dimensions")+
  theme_minimal()

```

```{r}
# --- aes is reserved to mapping variable to chart estetics, based on the chart variable.
# --- if the changes are not based on a variable it should be outside the aes

ggplot(data.frame(penguins), aes(x = body_mass_g, 
                                 y = flipper_length_mm), 
       color="red") +
  geom_point() +
  labs(x = "Flipper length, mm", 
       y = "Body mass, g", 
       title = "Palmer penguins body dimensions") +
  theme_minimal()
```
